logging:
  level:
    root: INFO

service:
  address:
    auth: 'localhost:3000'
    bill: 'localhost:3000'
    delivery: 'localhost:3000'

server:
  tomcat:
    max-connections: 100000
    accept-count: 100000
